version: '3.0'

services:
  datingdb:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: datingappschema
      MYSQL_USER: datingappuser
      MYSQL_PASSWORD: password
    # healthcheck:
    #   test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
    #   timeout: 20s
    #   retries: 10
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySql_Init_Script:/docker-entrypoint-initdb.d
    # restart: always

  datingapp:
    depends_on:
      - datingdb
    image: teo/datingapp:runtime
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DatingDbConnection=Server=datingdb;Database=datingappschema;Uid=datingappuser;Pwd=password;
    env_file: ./datingapp.env
    build:
      context: .
    ports:
      - '8080:80'

volumes:
  dbdata:
